import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "React Developer Assignment",
  description: "Generated by Md. Nafis Tarik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
